### ISSUE TITLE
aqi_EPAAQI_description

### ISSUE THREAD

**Issue by MksRasp** [bellrichm/weewx-aqi-xtype#11]
Hi
just installed **weewx-aqi-xtype v1.2.0-rc01** and we are using its default skin, the web page is displaying the aqi description as blow:

1st FL AQI (Nowcast): 15 (aqi_EPAAQI_description 1)
1st FL AQI: 14 (aqi_EPAAQI_description 1)

 I believe it should display (Normal) instead of (aqi_EPAAQI_description 1), how to fix it.

thank you

**Comment by bellrichm** [comment]
Thanks for catching. This will be part of v2.
