### ISSUE TITLE
Default Formatting for AQI

### ISSUE THREAD

**Issue by dshanske** [bellrichm/weewx-aqi-xtype#2]
By default, the air quality index shows with decimal...I know I can manually set it, but shouldn't the default be a whole number?

**Comment by bellrichm** [comment]
Yeah, I was just noticing this. I'll have to do some learning. This should be something I can fix.

**Comment by dshanske** [comment]
Tell me if there's anything I can do to test or help

**Comment by bellrichm** [comment]
At the moment, nothing specific. Your willingness to try it out and provide feedback is a big help.

**Comment by bellrichm** [comment]
Fixed in 1.0.3
